wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.5
      5: 0.10.32
      8:
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 16
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache_images:
  desc: null
  value: false
cfg:
  desc: null
  value: models/v5Lite-s.yaml
data:
  desc: null
  value: data/VisDrone.yaml
data_dict:
  desc: null
  value:
    names:
    - pedestrian
    - people
    - bicycle
    - car
    - van
    - truck
    - tricycle
    - awning-tricycle
    - bus
    - motor
    nc: 10
    test: ../VisDrone/VisDrone2019-DET-test-dev/images
    train: ../VisDrone/train/images
    val: ../VisDrone/val/images
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 300
evolve:
  desc: null
  value: false
exist_ok:
  desc: null
  value: false
global_rank:
  desc: null
  value: -1
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.001
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 0.2
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
img_size:
  desc: null
  value:
  - 640
  - 640
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
notest:
  desc: null
  value: false
opt:
  desc: null
  value:
    adam: false
    artifact_alias: latest
    batch_size: 16
    bbox_interval: -1
    bucket: ''
    cache_images: false
    cfg: models/v5Lite-s.yaml
    data: data/VisDrone.yaml
    device: ''
    entity: null
    epochs: 300
    evolve: false
    exist_ok: false
    global_rank: -1
    hyp:
      anchor_t: 4.0
      box: 0.05
      cls: 0.5
      cls_pw: 1.0
      degrees: 0.0
      fl_gamma: 0.0
      fliplr: 0.5
      flipud: 0.0
      hsv_h: 0.015
      hsv_s: 0.7
      hsv_v: 0.4
      iou_t: 0.2
      lr0: 0.001
      lrf: 0.2
      mixup: 0.0
      momentum: 0.937
      mosaic: 0.2
      obj: 1.0
      obj_pw: 1.0
      perspective: 0.0
      scale: 0.5
      shear: 0.0
      translate: 0.1
      warmup_bias_lr: 0.1
      warmup_epochs: 3.0
      warmup_momentum: 0.8
      weight_decay: 0.0005
    image_weights: false
    img_size:
    - 640
    - 640
    label_smoothing: 0.0
    linear_lr: false
    local_rank: -1
    multi_scale: false
    name: exp
    noautoanchor: false
    nosave: false
    notest: false
    project: runs/train
    quad: false
    rect: false
    resume: false
    save_dir: runs/train/exp4
    save_period: -1
    single_cls: false
    sync_bn: false
    total_batch_size: 16
    upload_dataset: false
    weights: weights/v5lite-s.pt
    workers: 8
    world_size: 1
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/exp4
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
total_batch_size:
  desc: null
  value: 16
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: weights/v5lite-s.pt
workers:
  desc: null
  value: 8
world_size:
  desc: null
  value: 1
